# Generated by Django 5.2.6 on 2025-09-08 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
